apiVersion: v1
kind: Jaeger
metadata:
  name: simplest
---

apiVersion: v1
kind: Service
metadata:
  name: jaeger-query-external
  namespace: observability
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 16686
      protocol: TCP
  selector:
    app: jaeger
    component: query
